baseURL = "https://almiraj.xyz"
disqusShortname = ""
enableGitInfo = false
enableRobotsTXT = true
hasCJKLanguage = true
rssLimit = 10
theme = "hugo-texify3"
title = "Almiraj"

[pagination]
pagerSize = 5

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  # title="TeXify3" removed to allow using site title
  author = "Ezzeldin"
  description = "Personal blog of Ezzeldin - Almiraj"
  footnote = """
  Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a>
  """
  customCSS = []
  customJS = []
  dateFormat = "2 January 2006"
  emphasisWithDots = true
  toc = true
  rootFontSize = "105%"
  math = true
  numberedSubtitles = true

  [params.commentEngine]
  code = """
  <script src="https://giscus.app/client.js"
        data-repo="AnonMiraj/almiraj-blog.git"
        data-repo-id="R_kgDOIjPNaQ"
        data-category="General"
        data-category-id="DIC_kwDOIjPNac4CaklA"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
  </script>
  """


[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    languageDirection = "ltr"
    title = "Almiraj"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Blog"
        url = "/posts/"
        weight = 1
        pre = """<svg width="1em" height="1em" viewBox="-2 -2 24 24" preserveAspectRatio="xMinYMin" class="jam jam-write"><path fill="currentColor" d="M5.72 14.456l1.761-.508 10.603-10.73a.456.456.0 00-.003-.64l-.635-.642a.443.443.0 00-.632-.003L6.239 12.635l-.52 1.82zM18.703.664l.635.643c.876.887.884 2.318.016 3.196L8.428 15.561l-3.764 1.084a.901.901.0 01-1.11-.623.915.915.0 01-.002-.506l1.095-3.84L15.544.647a2.215 2.215.0 013.159.016zM7.184 1.817c.496.0.898.407.898.909a.903.903.0 01-.898.909H3.592c-.992.0-1.796.814-1.796 1.817v10.906c0 1.004.804 1.818 1.796 1.818h10.776c.992.0 1.797-.814 1.797-1.818v-3.635c0-.502.402-.909.898-.909s.898.407.898.91v3.634c0 2.008-1.609 3.636-3.593 3.636H3.592C1.608 19.994.0 18.366.0 16.358V5.452c0-2.007 1.608-3.635 3.592-3.635h3.592z"/></svg>"""
      [[languages.en.menu.main]]
        name = "GitHub"
        url = "https://github.com/AnonMiraj"
        weight = 2
        pre = """<svg width="1em" height="1em" viewBox="0 0 24 24" data-name="Layer 1"><path fill="currentColor" d="M10.07031 20.50291a1.00008 1.00008.0 00-1.18115-.9834c-1.30908.24024-2.96191.27637-3.40137-.958a5.70754 5.70754.0 00-1.83691-2.415 1.20073 1.20073.0 01-.1665-.10938 1 1 0 00-.93067-.64551H2.54883a.99965.99965.0 00-1 .99512c-.00391.81543.811 1.33789 1.1416 1.51465a4.4408 4.4408.0 01.92383 1.35937c.36426 1.02344 1.42285 2.57617 4.46582 2.376.001.03516.00195.06836.00244.09863l.00439.26758a1 1 0 002 0l-.00488-.31836C10.07715 21.4951 10.07031 21.22068 10.07031 20.50291zm10.667-15.126c.03174-.125.063-.26367.09034-.41992a6.27792 6.27792.0 00-.40821-3.293 1.002 1.002.0 00-.61572-.58007c-.356-.12012-1.67041-.35645-4.18408 1.25a13.86918 13.86918.0 00-6.354.0C6.76221.751 5.45459.9658 5.10205 1.07908a.99744.99744.0 00-.63135.584 6.3003 6.3003.0 00-.40332 3.35644c.02442.12793.05078.2461.07813.35449A6.26928 6.26928.0 002.89014 9.20311a8.42168 8.42168.0 00.04248.92187c.334 4.60254 3.334 5.98438 5.42431 6.459-.04345.125-.083.25878-.11816.40039a1.00023 1.00023.0 001.94238.47851 1.6784 1.6784.0 01.46778-.87793.99947.99947.0 00-.5459-1.74512c-3.4541-.39453-4.95362-1.80175-5.1792-4.89843a6.61076 6.61076.0 01-.03369-.73828 4.25769 4.25769.0 01.91943-2.71289 3.022 3.022.0 01.1958-.23145.99988.99988.0 00.188-1.02441A3.3876 3.3876.0 016.0381 4.6787 4.09356 4.09356.0 016.1167 3.06346a7.54263 7.54263.0 012.415 1.17968 1.00877 1.00877.0 00.82764.13282 11.77716 11.77716.0 016.17285.001 1.00549 1.00549.0 00.83056-.13769 7.572 7.572.0 012.40528-1.19043 4.03977 4.03977.0 01.0874 1.57812 3.205 3.205.0 01-.16895.60743.9999.9999.0 00.188 1.02441c.07715.08691.1543.18066.22363.26855A4.12186 4.12186.0 0120 9.20311a7.03888 7.03888.0 01-.0376.77734c-.22021 3.05566-1.72558 4.46387-5.1958 4.85937a1 1 0 00-.54541 1.7461 1.63079 1.63079.0 01.46631.9082 3.06079 3.06079.0 01.09229.81934v2.334C14.77 21.2949 14.77 21.78025 14.77 22.00291a1 1 0 102 0c0-.2168.0-.69238.00977-1.33984V18.31346a4.8815 4.8815.0 00-.15479-1.31153 4.25638 4.25638.0 00-.11621-.416 6.51258 6.51258.0 005.44531-6.42383A8.69677 8.69677.0 0022 9.20311 6.13062 6.13062.0 0020.7373 5.37693z"/></svg>"""
      [[languages.en.menu.main]]
        name = "LinkedIn"
        url = "https://linkedin.com/in/ezz-eldean/"
        weight = 3
        pre = """<svg width="1em" height="1em" viewBox="0 0 24 24" data-name="Layer 1"><path fill="currentColor" d="M6 2C3.79086 2 2 3.79086 2 6V18c0 2.2091 1.79086 4 4 4H18c2.2091.0 4-1.7909 4-4V6c0-2.20914-1.7909-4-4-4H6zM4 6c0-1.10457.89543-2 2-2H18c1.1046.0 2 .89543 2 2V18C20 19.1046 19.1046 20 18 20H6C4.89543 20 4 19.1046 4 18V6zm5 5C9 10.4477 8.55228 10 8 10S7 10.4477 7 11v6C7 17.5523 7.44772 18 8 18S9 17.5523 9 17V11zm.5-3.5C9.5 8.32843 8.82843 9 8 9 7.17157 9 6.5 8.32843 6.5 7.5 6.5 6.67157 7.17157 6 8 6s1.5.67157 1.5 1.5zM12 10C12.3395 10 12.6395 10.1692 12.8203 10.4279 13.3329 10.1502 13.9036 10 14.5 10c2.1594.0 3.5 1.9258 3.5 3.5714V17c0 .5523-.4477 1-1 1s-1-.4477-1-1v-3.4286C16 12.8032 15.3406 12 14.5 12 13.9759 12 13.3974 12.2849 13 12.9631V17c0 .5523-.4477 1-1 1s-1-.4477-1-1v-6c0-.5523.4477-1 1-1z"/></svg>"""
      [[languages.en.menu.main]]
        name = "RSS"
        url = "/index.xml"
        weight = 4
        pre = """<svg class="rss-icon" width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M2.88,16.88a3,3,0,0,0,0,4.24,3,3,0,0,0,4.24,0,3,3,0,0,0-4.24-4.24Zm2.83,2.83a1,1,0,0,1-1.42-1.42,1,1,0,0,1,1.42,0A1,1,0,0,1,5.71,19.71ZM5,12a1,1,0,0,0,0,2,5,5,0,0,1,5,5,1,1,0,0,0,2,0,7,7,0,0,0-7-7ZM5,8a1,1,0,0,0,0,2,9,9,0,0,1,9,9,1,1,0,0,0,2,0,11.08,11.08,0,0,0-3.22-7.78A11.08,11.08,0,0,0,5,8Zm10.61.39A15.11,15.11,0,0,0,5,4,1,1,0,0,0,5,6,13,13,0,0,1,18,19a1,1,0,0,0,2,0A15.11,15.11,0,0,0,15.61,8.39Z"/></svg>"""

  [languages.ar]
    languageName = "العربية"
    weight = 2
    languageDirection = "rtl"
    title = "المعراج"
    [languages.ar.menu]
      [[languages.ar.menu.main]]
        name = "المقالات"
        url = "/posts/"
        weight = 1
        pre = """<svg width="1em" height="1em" viewBox="-2 -2 24 24" preserveAspectRatio="xMinYMin" class="jam jam-write"><path fill="currentColor" d="M5.72 14.456l1.761-.508 10.603-10.73a.456.456.0 00-.003-.64l-.635-.642a.443.443.0 00-.632-.003L6.239 12.635l-.52 1.82zM18.703.664l.635.643c.876.887.884 2.318.016 3.196L8.428 15.561l-3.764 1.084a.901.901.0 01-1.11-.623.915.915.0 01-.002-.506l1.095-3.84L15.544.647a2.215 2.215.0 013.159.016zM7.184 1.817c.496.0.898.407.898.909a.903.903.0 01-.898.909H3.592c-.992.0-1.796.814-1.796 1.817v10.906c0 1.004.804 1.818 1.796 1.818h10.776c.992.0 1.797-.814 1.797-1.818v-3.635c0-.502.402-.909.898-.909s.898.407.898.91v3.634c0 2.008-1.609 3.636-3.593 3.636H3.592C1.608 19.994.0 18.366.0 16.358V5.452c0-2.007 1.608-3.635 3.592-3.635h3.592z"/></svg>"""
      [[languages.ar.menu.main]]
        name = "جت هب"
        url = "https://github.com/AnonMiraj"
        weight = 2
        pre = """<svg width="1em" height="1em" viewBox="0 0 24 24" data-name="Layer 1"><path fill="currentColor" d="M10.07031 20.50291a1.00008 1.00008.0 00-1.18115-.9834c-1.30908.24024-2.96191.27637-3.40137-.958a5.70754 5.70754.0 00-1.83691-2.415 1.20073 1.20073.0 01-.1665-.10938 1 1 0 00-.93067-.64551H2.54883a.99965.99965.0 00-1 .99512c-.00391.81543.811 1.33789 1.1416 1.51465a4.4408 4.4408.0 01.92383 1.35937c.36426 1.02344 1.42285 2.57617 4.46582 2.376.001.03516.00195.06836.00244.09863l.00439.26758a1 1 0 002 0l-.00488-.31836C10.07715 21.4951 10.07031 21.22068 10.07031 20.50291zm10.667-15.126c.03174-.125.063-.26367.09034-.41992a6.27792 6.27792.0 00-.40821-3.293 1.002 1.002.0 00-.61572-.58007c-.356-.12012-1.67041-.35645-4.18408 1.25a13.86918 13.86918.0 00-6.354.0C6.76221.751 5.45459.9658 5.10205 1.07908a.99744.99744.0 00-.63135.584 6.3003 6.3003.0 00-.40332 3.35644c.02442.12793.05078.2461.07813.35449A6.26928 6.26928.0 002.89014 9.20311a8.42168 8.42168.0 00.04248.92187c.334 4.60254 3.334 5.98438 5.42431 6.459-.04345.125-.083.25878-.11816.40039a1.00023 1.00023.0 001.94238.47851 1.6784 1.6784.0 01.46778-.87793.99947.99947.0 00-.5459-1.74512c-3.4541-.39453-4.95362-1.80175-5.1792-4.89843a6.61076 6.61076.0 01-.03369-.73828 4.25769 4.25769.0 01.91943-2.71289 3.022 3.022.0 01.1958-.23145.99988.99988.0 00.188-1.02441A3.3876 3.3876.0 016.0381 4.6787 4.09356 4.09356.0 016.1167 3.06346a7.54263 7.54263.0 012.415 1.17968 1.00877 1.00877.0 00.82764.13282 11.77716 11.77716.0 016.17285.001 1.00549 1.00549.0 00.83056-.13769 7.572 7.572.0 012.40528-1.19043 4.03977 4.03977.0 01.0874 1.57812 3.205 3.205.0 01-.16895.60743.9999.9999.0 00.188 1.02441c.07715.08691.1543.18066.22363.26855A4.12186 4.12186.0 0120 9.20311a7.03888 7.03888.0 01-.0376.77734c-.22021 3.05566-1.72558 4.46387-5.1958 4.85937a1 1 0 00-.54541 1.7461 1.63079 1.63079.0 01.46631.9082 3.06079 3.06079.0 01.09229.81934v2.334C14.77 21.2949 14.77 21.78025 14.77 22.00291a1 1 0 102 0c0-.2168.0-.69238.00977-1.33984V18.31346a4.8815 4.8815.0 00-.15479-1.31153 4.25638 4.25638.0 00-.11621-.416 6.51258 6.51258.0 005.44531-6.42383A8.69677 8.69677.0 0022 9.20311 6.13062 6.13062.0 0020.7373 5.37693z"/></svg>"""
      [[languages.ar.menu.main]]
        name = "لينكيدين"
        url = "https://linkedin.com/in/ezz-eldean/"
        weight = 3
        pre = """<svg width="1em" height="1em" viewBox="0 0 24 24" data-name="Layer 1"><path fill="currentColor" d="M6 2C3.79086 2 2 3.79086 2 6V18c0 2.2091 1.79086 4 4 4H18c2.2091.0 4-1.7909 4-4V6c0-2.20914-1.7909-4-4-4H6zM4 6c0-1.10457.89543-2 2-2H18c1.1046.0 2 .89543 2 2V18C20 19.1046 19.1046 20 18 20H6C4.89543 20 4 19.1046 4 18V6zm5 5C9 10.4477 8.55228 10 8 10S7 10.4477 7 11v6C7 17.5523 7.44772 18 8 18S9 17.5523 9 17V11zm.5-3.5C9.5 8.32843 8.82843 9 8 9 7.17157 9 6.5 8.32843 6.5 7.5 6.5 6.67157 7.17157 6 8 6s1.5.67157 1.5 1.5zM12 10C12.3395 10 12.6395 10.1692 12.8203 10.4279 13.3329 10.1502 13.9036 10 14.5 10c2.1594.0 3.5 1.9258 3.5 3.5714V17c0 .5523-.4477 1-1 1s-1-.4477-1-1v-3.4286C16 12.8032 15.3406 12 14.5 12 13.9759 12 13.3974 12.2849 13 12.9631V17c0 .5523-.4477 1-1 1s-1-.4477-1-1v-6c0-.5523.4477-1 1-1z"/></svg>"""
      [[languages.ar.menu.main]]
        name = "RSS"
        url = "/index.xml"
        weight = 4
        pre = """<svg class="rss-icon" width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M2.88,16.88a3,3,0,0,0,0,4.24,3,3,0,0,0,4.24,0,3,3,0,0,0-4.24-4.24Zm2.83,2.83a1,1,0,0,1-1.42-1.42,1,1,0,0,1,1.42,0A1,1,0,0,1,5.71,19.71ZM5,12a1,1,0,0,0,0,2,5,5,0,0,1,5,5,1,1,0,0,0,2,0,7,7,0,0,0-7-7ZM5,8a1,1,0,0,0,0,2,9,9,0,0,1,9,9,1,1,0,0,0,2,0,11.08,11.08,0,0,0-3.22-7.78A11.08,11.08,0,0,0,5,8Zm10.61.39A15.11,15.11,0,0,0,5,4,1,1,0,0,0,5,6,13,13,0,0,1,18,19a1,1,0,0,0,2,0A15.11,15.11,0,0,0,15.61,8.39Z"/></svg>"""
